In [1]:
# -*- coding: utf8 -*-
import os
import time
import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
import openturns as ot
from openturns.viewer import View
import json
import requests

In [2]:
from otbenchmark import evaluate

In [3]:
help(evaluate)

Help on module otbenchmark.evaluate in otbenchmark:

NAME
    otbenchmark.evaluate

FUNCTIONS
    evaluate(username, password, set_id, problem_id, x)
        Evaluate a performance function
        
        Parameters
        ----------
            username : str
                Registered username for authentication. For testing without registration use 'testuser'.
            password : str
                Registered password for authentication. For testing without registration use 'testpass'.
            set_id : int
                Identification number of the problem set.
            problem_id : int
                Identification number of the problem.
            x : list, numpy.array
                Values of independent variables/random variables where the performance function is evaluated. Columns are the values of random variables (x1, x2,...xn). Bundle (vectorized) call is possible by providing multiple rows, each corresponds to one set of values of the random variables.
  

In [4]:
username = 'testuser'
password = 'testpass'
set_id = -1
problem_id  = 1
x = [-1.]*6

In [5]:
g_val_sys, g_val_comp, msg = evaluate.evaluate(username, password, set_id, problem_id, x)

In [22]:
def g_fun(x):
    x = np.array(x)
    g_val_sys, g_val_comp, msg = evaluate.evaluate(username, password, set_id, problem_id, x)
    return g_val_comp

In [23]:
y = g_fun(x)
y

[-1. -1. -1. -1. -1. -1.]
[4.0]


[4.0]

In [24]:
y[0]

4.0

In [25]:
myFunction = ot.PythonFunction(6, 1, g_fun)
myFunction(x)

[-1. -1. -1. -1. -1. -1.]
[4.0]


class=Point name=Unnamed dimension=1 values=[4]

In [26]:
dist_X1 = ot.LogNormal(120, 12)
dist_X2 = ot.LogNormal(120, 12)
dist_X3 = ot.LogNormal(120, 12)
dist_X4 = ot.LogNormal(120, 12)
dist_X5 = ot.LogNormal(50, 10)
dist_X6 = ot.LogNormal(40, 8)
myDistribution = ot.ComposedDistribution([dist_X1, dist_X2, dist_X3, \
                                         dist_X4, dist_X5, dist_X6])
myRandomVector = ot.RandomVector(myDistribution)

In [27]:
myFunction = ot.PythonFunction(6, 1, g_fun)
myOutputVector = ot.CompositeRandomVector(myFunction, myRandomVector)
#myOutputVector.getSample(10)

In [ ]:
event = ot.Event(myOutputVector, ot.LessOrEqual(), 0.0)
# We create an OptimizationAlgorithm algorithm
solver = ot.SQP()
algo = ot.SORM(solver, event, [1]*6)
algo.run()
result = algo.getResult()

[1. 1. 1. 1. 1. 1.]
[-4.0]
[1.00001 1.      1.      1.      1.      1.     ]
[-3.9999899864196777]
[0.99999 1.      1.      1.      1.      1.     ]
[-4.000010013580322]
[1.      1.00001 1.      1.      1.      1.     ]
[-3.9999799728393555]
[1.      0.99999 1.      1.      1.      1.     ]
[-4.0000200271606445]
[1.      1.      1.00001 1.      1.      1.     ]
[-3.9999799728393555]
[1.      1.      0.99999 1.      1.      1.     ]
[-4.0000200271606445]
[1.      1.      1.      1.00001 1.      1.     ]
[-3.9999899864196777]
[1.      1.      1.      0.99999 1.      1.     ]
[-4.000010013580322]
[1.      1.      1.      1.      1.00001 1.     ]
[-4.000050067901611]
[1.      1.      1.      1.      0.99999 1.     ]
[-3.9999499320983887]
[1.      1.      1.      1.      1.      1.00001]
[-4.000050067901611]
[1.      1.      1.      1.      1.      0.99999]
[-3.9999499320983887]
[1. 1. 1. 1. 1. 1.]
[-4.0]
[1.0001 1.0001 1.     1.     1.     1.    ]
[-3.9997000694274902]
[0.9999 1.0001 1.   

[17.72098731994629]
[9.50545364 1.42273802 1.90372266 6.14695634 1.4365092  1.19456665]
[9.149951934814453]
[7.4650093  2.7384149  3.16766044 6.00307809 2.13075561 1.68140152]
[6.219453811645508]
[6.61544564 3.79914969 4.08607272 5.93240682 2.59505313 1.99481195]
[5.368973731994629]
[6.22763974 4.47486547 4.64076767 5.89738379 2.86386513 2.17278735]
[5.173027038574219]
[6.0423471  4.85653779 4.9457447  5.87994989 3.00853948 2.26764389]
[5.1459455490112305]
[5.95177855 5.05941341 5.10566867 5.87125227 3.08359471 2.31661397]
[5.152153968811035]
[5.90700462 5.1640075  5.18755955 5.86690829 3.1218216  2.34149416]
[5.160469055175781]
[5.88474413 5.21711264 5.22899623 5.8647375  3.14111238 2.35403428]
[5.165966987609863]
[5.87364536 5.24386965 5.24983852 5.86365241 3.15080243 2.3603295 ]
[5.1690521240234375]
[5.86810383 5.25729957 5.2602908  5.86310994 3.15565866 2.36348342]
[5.170680999755859]
[5.86533502 5.26402743 5.26552474 5.86283873 3.15808958 2.36506196]
[5.171520233154297]
[5.8639511

[0.8026928901672363]
[0.3974539  0.43818506 0.44471675 2.22466085 0.37461119 0.34242792]
[0.8027229309082031]
[0.3974539  0.43818506 0.44471675 2.22464085 0.37461119 0.34242792]
[0.8027029037475586]
[0.3974539  0.43818506 0.44471675 2.22465085 0.37462119 0.34242792]
[0.8026628494262695]
[0.3974539  0.43818506 0.44471675 2.22465085 0.37460119 0.34242792]
[0.8027629852294922]
[0.3974539  0.43818506 0.44471675 2.22465085 0.37461119 0.34243792]
[0.8026628494262695]
[0.3974539  0.43818506 0.44471675 2.22465085 0.37461119 0.34241792]
[0.8027628660202026]
[0.38234063 0.24032672 0.24006224 1.56816143 0.27622946 0.25623795]
[0.24894297122955322]
[0.38235063 0.24032672 0.24006224 1.56816143 0.27622946 0.25623795]
[0.2489529848098755]
[0.38233063 0.24032672 0.24006224 1.56816143 0.27622946 0.25623795]
[0.24893295764923096]
[0.38234063 0.24033672 0.24006224 1.56816143 0.27622946 0.25623795]
[0.24896299839019775]
[0.38234063 0.24031672 0.24006224 1.56816143 0.27622946 0.25623795]
[0.248922944068908

[0.0029507875442504883]
[0.24787272 0.1677619  0.16749    1.17785806 0.21610889 0.20252791]
[0.0030508041381835938]
[0.23428159 0.15620622 0.15583834 1.09092538 0.2011074  0.18889706]
[-0.0007263422012329102]
[0.24098136 0.16188098 0.16155916 1.13355867 0.20847325 0.1955986 ]
[0.0010609626770019531]
[0.24440275 0.16479521 0.16449785 1.15549609 0.21225674 0.19903802]
[0.002011239528656006]
[0.24613162 0.16627194 0.16598719 1.1666235  0.21417416 0.20078034]
[0.00250089168548584]
[0.24700063 0.16701526 0.1667369  1.17222732 0.21513935 0.20165721]
[0.0027494430541992188]
[0.24743629 0.16738817 0.16711303 1.17503932 0.21562358 0.20209708]
[0.002874612808227539]
[0.24765441 0.16757493 0.16730141 1.17644784 0.2158661  0.20231737]
[0.0029374361038208008]
[0.24776354 0.16766839 0.16739568 1.17715274 0.21598746 0.20242761]
[0.002969026565551758]
[0.24781812 0.16771514 0.16744283 1.17750535 0.21604817 0.20248275]
[0.0029848814010620117]
[0.24784542 0.16773852 0.16746641 1.17768169 0.21607853 0.20

In [ ]:
print(result.getEventProbabilityBreitung(),
result.getEventProbabilityHohenBichler(),
result.getEventProbabilityTvedt())

In [ ]:
optres = result.getOptimizationResult()
print(
"Design point:", optres.getOptimalPoint(),"\n" 
"Absolute error:", optres.getAbsoluteError(),"\n"#norme inifnie entre Xn et Xn+1
"Residual error:", optres.getResidualError() ,"\n" 
"Evaluation number:", optres.getEvaluationNumber())